### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by cdfx2016** [saulmm/From-design-to-Android-part1#1]
When I downloaded from this site, the following error occurred when compiling the project。

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.android.support.constraint:constraint-layout:1.0.2.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/constraint/constraint-layout/1.0.2/constraint-layout-1.0.2.pom
         https://jcenter.bintray.com/com/android/support/constraint/constraint-layout/1.0.2/constraint-layout-1.0.2.jar
     Required by:
         project :app

**Comment by saulmm** [comment]
Did you check that you have the latest version of the ConstraintLayout in the SDK manager?

<img width="1036" alt="screen shot 2017-03-20 at 14 18 53" src="https://cloud.githubusercontent.com/assets/3531999/24101335/2dd4b2a0-0d78-11e7-8f58-255d85419a1c.png">

**Comment by cdfx2016** [comment]
Thank you for your solution.
