### ISSUE TITLE
Unable to open HomeActivity

### ISSUE THREAD

**Issue by Arkar-Aung** [saulmm/From-design-to-Android-part1#2]
After building project is success, the app crashes immediately right after launching.

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saulmm.cui/com.saulmm.cui.HomeActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by saulmm** [comment]
If you build from [this commit](https://github.com/saulmm/from_design_to_android_part1/commit/b456ef19ef81c725c6685cac3999bfa5fd7d792a) which is the head in master at a time, you shouldn't have that problem.

Anyway, that used to happen when your activity is inheriting from [AppCompatActivity](https://developer.android.com/reference/android/support/v7/app/AppCompatActivity.html) but the theme set to it is not related with AppCompat

i.e:

This will crash firing your exception
`<style name="AppTheme" parent="@android:style/Theme.Material">` 
`HomeActivity extends AppCompatActivity`

This will work
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">` 
`HomeActivity extends AppCompatActivity`

**Comment by NanBox** [comment]
I have the same problem. In AdnroidManifest.xml, I change
```
android:theme="@style/AppTheme" 
```
to
```
android:theme="@style/Base.AppTheme"
```
It work for me.

**Comment by Arkar-Aung** [comment]
Yes,`AppTheme` which inherits from `Base.AppTheme` is declared only for v23. That's why.

**Comment by saulmm** [comment]
@Arkar-Aung is right, what a mistake, solved [here](https://github.com/saulmm/android_coding_challenges1/commit/491166904e6b702352e5a12716a3bf16ded80c75). Thanks for the feedback guys
