### ISSUE TITLE
Activity Binding

### ISSUE THREAD

**Issue by chemickypes** [saulmm/From-design-to-Android-part1#6]
I don't find this class **com.saulmm.cui.databinding.ActivityHomeBinding**. I'd like to see because it will be very interesting!

**Comment by saulmm** [comment]
Hello! 

ActivityHomeBinding is an autogenerated class by the [Databinding library](https://developer.android.com/topic/libraries/data-binding/index.html), That activity refers to the `activity_home.xml` file, and it's under the build folder. That's the reason because you don't find it :)

**Comment by chemickypes** [comment]
Hi @saulmm, thanks, I did't know this library. Wow, it's very good! Thank you!

**Comment by saulmm** [comment]
👍
